language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install tox
# command to run tests
script:
  - tox